### PR TITLE
Fixed username followed by a punctuation character notification

### LINKED ISSUE #925: Notification doesn't work if @name is followed by a dot
In this status :
http://www.app.tatamisoft.com/#/home/status/46dcf2c0-1bf9-11e5-beec-fe54008898dc
And @sbergia was not notified

I made few tests (deleted now) : I think the problem was that I put a dot just after its login

If not, ponctuation marks should be ignored from the @xxx parsing

Please note, that in the web ui, when the status is rendered, the link points correctly to sbergia home page.

### PR DESCRIPTION
**Pull request by raphaelbrugier**
fixes #925

As discussed by mail, this is a fix with a unit test for this issue

### CODE REVIEW

**Comment by bescott1** [comment]
@raphaelbrugier I accepted the pull request, however when running mvn test, your test shouldMentionUser() fails:

Failed tests: 
  StatusUpdateServiceTest.shouldMentionUser:68 
Expected: is <1>
     but: was <0>

Is there anything I'm missing?

**Comment by raphaelbrugier** [comment]
Oh god, my mistake. There is a typo on the "content" declaration L.63
It should me "Hello @jane! @john ! world"
Somehow I've mistype the extra "e" before commiting. 

As it's already merged on the master, do you think we can edit the commit ?

**Comment by bescott1** [comment]
I fixed the test straight on master so we don't have to do another pull request.

Thanks, I should have caught the typo :)

**Comment by raphaelbrugier** [comment]
Hi, ok thanks and sorry again for the typo.

To avoid these kinds of failing pull request, I think a setup of Travis CI to validate the pull requests would be great : http://docs.travis-ci.com/user/pull-requests/

**Pull request merged**
